class ProductError(Exception): ...
class NonExistingProductError(ProductError): ...

class ClientError(Exception): ...

class UnsupportedSearchTypeError(Exception): ...

class TransactionTypeError(Exception): ...